name: Deploy Automático para Hostgator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          #server-dir: / # Ajuste conforme a raiz que configurou no passo anterior
          protocol: ftps
          port: 21 # Força a comunicação na porta padrão de FTP
          timeout: 120000 # Aumenta o tempo limite de resposta (em milissegundos)
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**